### ISSUE TITLE
Inverted Display issue with JC4827W543R

### ISSUE THREAD

**Issue by slevon** [calint/arduino-bam#2]
Hello,
First thank you for this great source of utilizing the JC4827W543R board, it's a great help to get the board running and check it's capabilities. I have the very same board from Guition.

However I am facing an issue with the board and the source code you provided: 
The game is shown in inverted colours. 

I tried to set the inverted flag in the library but it doesn't seem to be a good approach, and also it doesn't work. 
How can I investigate the issue and where might I invert the display?
It seems strange that the very same board has inverted colours.

Any help would be greatly appreciated.

Best regards 
Roman

**Comment by calint** [comment]
The initiation of my board needs the command:
        `0x21, 0x00, // INVON, invert colors (displays correct colors on device)`
`(line 140 in /src/devices/JC4827W543R.hpp)`

Try commenting that line. I don't know why my board requires inversion of colors. :/

Best regards

**Comment by calint** [comment]
Project `arduiono-bam` is deprecated. I continued the exploration in `platformio-bam`.

Kind regards
